"""Layer 3 — Customer Database (customer facts only, no intelligence)."""

import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, Float, ForeignKey, String, Text, Uuid
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class Customer(Base):
    __tablename__ = "customers"

    customer_id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    upload_id: Mapped[uuid.UUID] = mapped_column(Uuid, ForeignKey("raw_upload.upload_id"), nullable=False)
    raw_row_id: Mapped[uuid.UUID | None] = mapped_column(Uuid, ForeignKey("raw_customer_data.id"), nullable=True)
    email: Mapped[str | None] = mapped_column(String(320), nullable=True, index=True)
    first_name: Mapped[str | None] = mapped_column(String(128), nullable=True)
    last_name: Mapped[str | None] = mapped_column(String(128), nullable=True)
    phone: Mapped[str | None] = mapped_column(String(64), nullable=True)
    address: Mapped[str | None] = mapped_column(String(512), nullable=True)
    city: Mapped[str | None] = mapped_column(String(128), nullable=True)
    state: Mapped[str | None] = mapped_column(String(8), nullable=True, index=True)
    zip: Mapped[str | None] = mapped_column(String(16), nullable=True, index=True)
    country: Mapped[str | None] = mapped_column(String(64), nullable=True)
    permission: Mapped[str | None] = mapped_column(String(64), nullable=True)
    sfmc_segment_id: Mapped[str | None] = mapped_column(String(32), nullable=True, index=True)
    sfmc_segment_code: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    sfmc_segment_name: Mapped[str | None] = mapped_column(String(128), nullable=True)
    audience_segment: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    is_duplicate: Mapped[bool] = mapped_column(Boolean, default=False)
    duplicate_type: Mapped[str | None] = mapped_column(String(32), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    upload = relationship("RawUpload", back_populates="customers")
    datalogix = relationship("CustomerDatalogix", back_populates="customer", uselist=False)
    intelligence = relationship("CustomerIntelligence", back_populates="customer", uselist=False)


class CustomerDatalogix(Base):
    """Datalogix codes stored as-is (X/Y/Z/U never converted to numbers)."""

    __tablename__ = "customer_datalogix"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    customer_id: Mapped[uuid.UUID] = mapped_column(Uuid, ForeignKey("customers.customer_id"), unique=True)
    age_range: Mapped[str | None] = mapped_column(String(32), nullable=True)
    generation: Mapped[str | None] = mapped_column(String(32), nullable=True)
    gender: Mapped[str | None] = mapped_column(String(16), nullable=True)
    estimated_income: Mapped[str | None] = mapped_column(String(32), nullable=True)
    home_value: Mapped[str | None] = mapped_column(String(32), nullable=True)
    household: Mapped[str | None] = mapped_column(String(64), nullable=True)
    length_of_residence: Mapped[str | None] = mapped_column(String(32), nullable=True)
    net_worth: Mapped[str | None] = mapped_column(String(8), nullable=True)
    online_access: Mapped[str | None] = mapped_column(String(8), nullable=True)
    retail_card: Mapped[str | None] = mapped_column(String(8), nullable=True)
    dwelling: Mapped[str | None] = mapped_column(String(32), nullable=True)
    bank_card: Mapped[str | None] = mapped_column(String(8), nullable=True)
    adults: Mapped[str | None] = mapped_column(String(16), nullable=True)
    children: Mapped[str | None] = mapped_column(String(16), nullable=True)
    persons: Mapped[str | None] = mapped_column(String(16), nullable=True)
    dma_code: Mapped[str | None] = mapped_column(String(8), nullable=True)
    county_code: Mapped[str | None] = mapped_column(String(8), nullable=True)

    customer = relationship("Customer", back_populates="datalogix")


class CustomerIntelligence(Base):
    """Derived intelligence — generated by engine, never user-entered."""

    __tablename__ = "customer_intelligence"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    customer_id: Mapped[uuid.UUID] = mapped_column(Uuid, ForeignKey("customers.customer_id"), unique=True)
    prizm_proxy_segment: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    ceragem_segment: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    message_direction: Mapped[str | None] = mapped_column(String(128), nullable=True)
    pain_index: Mapped[float | None] = mapped_column(nullable=True)
    purchase_power_index: Mapped[float | None] = mapped_column(nullable=True)
    lifestyle_index: Mapped[float | None] = mapped_column(nullable=True)
    email_response_index: Mapped[float | None] = mapped_column(nullable=True)
    brand_familiarity_index: Mapped[float | None] = mapped_column(nullable=True)
    recommended_product: Mapped[str | None] = mapped_column(String(64), nullable=True)
    expected_conversion: Mapped[float | None] = mapped_column(nullable=True)
    baseline_conversion: Mapped[float | None] = mapped_column(nullable=True)
    promo_uplift: Mapped[float | None] = mapped_column(nullable=True)
    baseline_revenue: Mapped[float | None] = mapped_column(nullable=True)
    expected_revenue: Mapped[float | None] = mapped_column(nullable=True)
    campaign_priority: Mapped[float | None] = mapped_column(nullable=True)
    price_resistance_score: Mapped[float | None] = mapped_column(nullable=True)
    recommended_promotion: Mapped[float | None] = mapped_column(nullable=True)
    promo_code: Mapped[str | None] = mapped_column(String(32), nullable=True)
    commercial_version: Mapped[str | None] = mapped_column(String(32), nullable=True)
    trace_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    framework_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    trace_summary_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    framework_summary_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    rule_version: Mapped[str | None] = mapped_column(String(32), nullable=True)
    calculation_version: Mapped[str | None] = mapped_column(String(64), nullable=True)
    engine_version: Mapped[str | None] = mapped_column(String(64), nullable=True)
    generated_by: Mapped[str | None] = mapped_column(String(128), nullable=True)
    generated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    customer = relationship("Customer", back_populates="intelligence")
