"""Volume 26 — CIOS Design Principles registry (SSOT / Project Constitution)."""

DESIGN_PRINCIPLES_VERSION = "Volume 26 v1.0"
DESIGN_PRINCIPLES_STATUS = "Final"
DESIGN_PRINCIPLES_SCOPE = "Every Module"

VISION = (
    "CIOS exists to transform customer information into business intelligence. "
    "The platform is not designed to manage customer records. "
    "The platform is designed to improve business decisions."
)

PRINCIPLES: tuple[dict, ...] = (
    {
        "id": "01",
        "title": "Customer Intelligence First",
        "summary": "Every feature shall improve Customer Intelligence before operational convenience.",
        "statement": "CIOS understands customers. Customer Intelligence is always the primary asset.",
    },
    {
        "id": "02",
        "title": "Intelligence Before Campaign",
        "summary": "Campaigns are created from Intelligence; Intelligence is never created from campaigns alone.",
        "statement": "Campaigns are temporary. Customer Intelligence is permanent.",
    },
    {
        "id": "03",
        "title": "Recommendation Must Be Explainable",
        "summary": "Every recommendation answers What, Why, Business Rules, Intelligence, and Confidence.",
        "statement": "No recommendation shall exist without explanation. Explainability is mandatory.",
    },
    {
        "id": "04",
        "title": "Raw Data Is Immutable",
        "summary": "Uploaded customer information represents historical truth and shall never be overwritten.",
        "statement": "Corrections generate new records. Historical data remains preserved.",
    },
    {
        "id": "05",
        "title": "Intelligence Is Versioned",
        "summary": "Generated Intelligence evolves; historical Intelligence does not.",
        "statement": "Every Intelligence calculation stores Rule Version, Engine Version, Timestamp, Confidence, and Generated By.",
    },
    {
        "id": "06",
        "title": "Business Rules Before AI",
        "summary": "Business Rules define business policy; AI assists but never replaces them.",
        "statement": "AI recommendations shall always remain bounded by approved Business Rules.",
    },
    {
        "id": "07",
        "title": "Metadata Driven Everything",
        "summary": "Configuration shall originate from metadata, never from source code.",
        "statement": "Reference Tables are the single source of configuration.",
    },
    {
        "id": "08",
        "title": "No Hard Coding",
        "summary": "Business values shall never be hard-coded in source code.",
        "statement": "All configurable values belong to Metadata or Reference Data.",
    },
    {
        "id": "09",
        "title": "One Definition Only",
        "summary": "Every business concept has one canonical definition referenced by every module.",
        "statement": "Duplication of business concept definitions is prohibited.",
    },
    {
        "id": "10",
        "title": "Deterministic Processing",
        "summary": "The same input shall always produce the same result unless rules or metadata version changes.",
        "statement": "Determinism is required for forecast, recommendation, segmentation, mapping, dashboard, and learning.",
    },
    {
        "id": "11",
        "title": "Learning Improves the Future",
        "summary": "Learning never modifies history; it influences future recommendations.",
        "statement": "Historical campaign records remain unchanged.",
    },
    {
        "id": "12",
        "title": "Dashboards Are Intelligence Systems",
        "summary": "Dashboards answer business questions and help users decide what to do next.",
        "statement": "Dashboards are not reports. They are decision systems.",
    },
    {
        "id": "13",
        "title": "Geography Is Business Intelligence",
        "summary": "ZIP codes and states are commercial opportunity indicators, not mere locations.",
        "statement": "Geographic Intelligence is treated as a first-class business asset.",
    },
    {
        "id": "14",
        "title": "High-Consideration Product Strategy",
        "summary": "CIOS is optimized for trust, education, consultation, and long consideration cycles.",
        "statement": "The platform is intentionally not optimized for impulse purchases.",
    },
    {
        "id": "15",
        "title": "Enterprise Before Convenience",
        "summary": "Shortcuts shall never replace architecture or long-term maintainability.",
        "statement": "Every implementation must favor scalability and consistency.",
    },
    {
        "id": "16",
        "title": "Security Is Built-In",
        "summary": "Authentication, authorization, audit, encryption, role management, and data protection from day one.",
        "statement": "Security is not an optional feature.",
    },
    {
        "id": "17",
        "title": "Every Action Is Auditable",
        "summary": "Important actions must leave an audit trail answering Who, When, What, and Why.",
        "statement": "No critical action shall occur without traceability.",
    },
    {
        "id": "18",
        "title": "Executive Decision Support",
        "summary": "The ultimate customer of CIOS is the executive making business decisions.",
        "statement": "Every feature shall improve executive decision quality.",
    },
    {
        "id": "19",
        "title": "Documentation Equals Source Code",
        "summary": "Documentation is part of the product and must evolve with implementation.",
        "statement": "No production change is complete until documentation is updated.",
    },
    {
        "id": "20",
        "title": "Simplicity Over Complexity",
        "summary": "Complex implementation may exist internally; user experience shall remain simple.",
        "statement": "Every workflow shall reduce unnecessary decisions.",
    },
    {
        "id": "21",
        "title": "Automation By Default",
        "summary": "The platform shall automate repetitive work whenever possible.",
        "statement": "Manual intervention is reserved for exceptions.",
    },
    {
        "id": "22",
        "title": "Platform Before Project",
        "summary": "CIOS is a reusable Customer Intelligence Platform, not a single-campaign tool.",
        "statement": "Every enhancement should strengthen the platform itself.",
    },
    {
        "id": "23",
        "title": "Continuous Consistency",
        "summary": "Future improvements increase capability without changing foundational concepts.",
        "statement": "Architecture evolves. Principles remain.",
    },
)

METADATA_DRIVEN_EXAMPLES: tuple[str, ...] = (
    "Field Mapping",
    "Provider Mapping",
    "Reference Data",
    "Dashboard Metrics",
    "Validation Rules",
    "Campaign Types",
    "Message Types",
)

NO_HARD_CODING_EXAMPLES: tuple[str, ...] = (
    "State",
    "ZIP",
    "Products",
    "Campaign Types",
    "Provider Fields",
    "Business Rules",
    "Dashboard Metrics",
)

CANONICAL_DEFINITIONS: tuple[str, ...] = (
    "Purchase Power",
    "Pain Index",
    "Campaign Priority",
    "Revenue",
    "Conversion",
)

DETERMINISTIC_DOMAINS: tuple[str, ...] = (
    "Forecast",
    "Recommendation",
    "Segmentation",
    "Mapping",
    "Dashboard",
    "Learning",
)

AUTOMATION_EXAMPLES: tuple[str, ...] = (
    "Header Detection",
    "Field Mapping",
    "Validation",
    "Data Standardization",
    "Recommendation",
    "Forecast",
    "Dashboard Refresh",
)

HIGH_CONSIDERATION_ATTRIBUTES: tuple[str, ...] = (
    "Trust",
    "Education",
    "Consultation",
    "Long consideration cycles",
    "Premium positioning",
)

SECURITY_CAPABILITIES: tuple[str, ...] = (
    "Authentication",
    "Authorization",
    "Audit",
    "Encryption",
    "Role Management",
    "Data Protection",
)

AUDIT_QUESTIONS: tuple[str, ...] = ("Who?", "When?", "What?", "Why?")

EXPLAINABILITY_FIELDS: tuple[str, ...] = (
    "What?",
    "Why?",
    "Which Business Rules?",
    "Which Intelligence?",
    "Which Confidence?",
)

INTELLIGENCE_VERSION_FIELDS: tuple[str, ...] = (
    "Rule Version",
    "Engine Version",
    "Timestamp",
    "Confidence",
    "Generated By",
)

CONSTITUTION: tuple[dict, ...] = (
    {
        "conflict": "implementation vs architecture",
        "resolution": "follow the architecture",
    },
    {
        "conflict": "convenience vs consistency",
        "resolution": "follow consistency",
    },
    {
        "conflict": "AI vs Business Rules",
        "resolution": "follow Business Rules",
    },
    {
        "conflict": "new features vs Customer Intelligence",
        "resolution": "protect Customer Intelligence",
    },
)

FINAL_STATEMENT = (
    "The purpose of CIOS is to create a repeatable, explainable and continuously improving "
    "Customer Intelligence Platform that enables better business decisions for high-consideration products. "
    "Customer Intelligence is the foundation. Everything else is an implementation."
)

DESIGN_PRINCIPLES_ACCEPTANCE_CRITERIA: tuple[str, ...] = (
    "All 23 principles are documented and indexed",
    "Principles are exposed via API for every module",
    "Runtime compliance checks validate core architectural alignment",
    "Constitution conflict resolutions are documented",
    "Vision and final statement are immutable project guidance",
    "Documentation volume is indexed in Knowledge Hub",
    "Acceptance tests verify principle registry and compliance",
)
